language: python
python:
- 2.7
env:
- DJANGO=">=1.6,<1.7"
- DJANGO=">=1.7,<1.8"
- DJANGO=">=1.8,<1.9"
- DJANGO=">=1.9,<1.10"
- DJANGO=">=1.10,<1.11"
- DJANGO=">=1.11,<1.12"
install:
- pip install gitversion
- pip install "Django${DJANGO}"
- pip install .
- pip install coveralls
script:
- python setup.py test
after_success:
- coveralls
matrix:
  include:
  - python: 2.6
    env: DJANGO=">=1.4,<1.5"
  - python: 3.3
    env: DJANGO=">=1.8,<1.9"
  - python: 3.4
    env: DJANGO=">=1.9,<1.10"
  - python: 3.5
    env: DJANGO=">=1.10,<1.11"
  - python: 3.5
    env: DJANGO=">=1.11,<1.12"
  - python: pypy3
    env: DJANGO=">=1.8,<1.9"
  - python: pypy
    env: DJANGO=">=1.9,<1.10"
deploy:
  provider: pypi
  user: ocadotechnology
  password:
    secure: "CChW0HgBIyFy8W6EnBJYW0Uy+hSV2v7ji73dhuLEdA/Pteb5YAmD/9ibpsC2TpyjOXfpjBMW+gzsWAUB3rkvU/Z6Rj4w9/VyeFBzz/Djo9Tr3xfVKvuug1C+rv/y2MxrZ4QDnecek4IqWnSVAc0yMFy1w4l3pfqoW7Rg2004/V/xjHCM7DaRG/4U+k2vbPX0VmEGXAVrAcQgJvsupPC4OEoOeMeLTcqVI8XhiOcOz/Av2fhXU+kdNNP04yXmJAmzKZRhtfwcNGmo1HtG9naHiem2JSQlu4na447Uq5uFVytVQbkQLZO9+hjZif79FN4qkHBvLk1bKvsJkBWcK0tGrjwk2yVrGYxq+8jpVqCdXRhD9YQmAmPi9Lbj7l50gq/2sdN6B2hph6bhnglCoNnw6LwgvAdXSSM1BUzTHtcD2TBNruIoyzNrFVTW2f/EtZyYjeewXiZygh2YqIhSxuqxC5znVvb7oPKpeBEa7MwSnUFVhZ9CgbACIhJg/99DyfdfekwcZOgTEHl/+aqZegsjyRgm3JXoqoBwR/Das1r/BNc4vurOCoTLT9qSQG6JQqAO7rFxOEr/LzdylogOo8Xs3SjXuuEjR0Xzdh87LNGSw+f5bSR4xzAW2YPw7xFDpUkfO33nqiL70AHbKvJrgqoSHNUAvM0Oe/A3MbusYbTplkc="
  distributions: "bdist_wheel sdist"
  on:
    all_branches: true
    repo: ocadotechnology/django-xapp-render
    tags: true
    condition: "$DJANGO = '>=1.11,<1.12'"
